apiVersion: v1
kind: Service
metadata:
  name: {{ Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ Chart.Name }}
  ports:
  - name: grpc
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.ports.containerPort }}
