containers:
     image: yukesh24/checkoutservice:2

ports:
  - containerPort: 5050

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  type: ClusterIP

replicas: 1