containers:
  image: yukesh24/shippingservice:4a2ebac
  containerPort: 50051

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

replicas: 1

service:
  type: ClusterIP