apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: tcp-redis
    port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
